set_property PACKAGE_PIN L5 [get_ports {gpio_rtl_0_tri_o[0]}]
set_property PACKAGE_PIN L4 [get_ports {gpio_rtl_0_tri_o[1]}]
set_property PACKAGE_PIN M4 [get_ports {gpio_rtl_0_tri_o[2]}]
set_property PACKAGE_PIN M2 [get_ports {gpio_rtl_0_tri_o[3]}]
set_property PACKAGE_PIN M1 [get_ports {gpio_rtl_0_tri_o[4]}]
set_property PACKAGE_PIN N3 [get_ports {gpio_rtl_0_tri_o[5]}]
set_property PACKAGE_PIN N2 [get_ports {gpio_rtl_0_tri_o[6]}]
set_property PACKAGE_PIN N1 [get_ports {gpio_rtl_0_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[0]}]

set_property PACKAGE_PIN N4 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0]


set_property PACKAGE_PIN N11 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
