set_property PACKAGE_PIN H5 [get_ports S0_0]
set_property IOSTANDARD LVCMOS33 [get_ports S0_0]
set_property PACKAGE_PIN H4 [get_ports S0_inv_0]
set_property IOSTANDARD LVCMOS33 [get_ports S0_inv_0]
set_property PACKAGE_PIN J5 [get_ports S1_0]
set_property IOSTANDARD LVCMOS33 [get_ports S1_0]
set_property PACKAGE_PIN J4 [get_ports S1_inv_0]
set_property IOSTANDARD LVCMOS33 [get_ports S1_inv_0]
set_property PACKAGE_PIN H2 [get_ports S2_0]
set_property IOSTANDARD LVCMOS33 [get_ports S2_0]
set_property PACKAGE_PIN H1 [get_ports S2_inv_0]
set_property IOSTANDARD LVCMOS33 [get_ports S2_inv_0]

set_property PACKAGE_PIN K1 [get_ports data_in_a0_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_in_a0_0]
set_property PACKAGE_PIN J1 [get_ports data_in_b0_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_in_b0_0]
set_property PACKAGE_PIN B7 [get_ports data_in_a1_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_in_a1_0]
set_property PACKAGE_PIN A7 [get_ports data_in_b1_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_in_b1_0]
set_property PACKAGE_PIN B6 [get_ports data_in_a2_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_in_a2_0]
set_property PACKAGE_PIN B5 [get_ports data_in_b2_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_in_b2_0]
set_property PACKAGE_PIN A5 [get_ports data_in_a3_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_in_a3_0]
set_property PACKAGE_PIN A4 [get_ports data_in_b3_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_in_b3_0]

set_property PACKAGE_PIN B4 [get_ports sclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports sclk_0]
set_property PACKAGE_PIN A3 [get_ports a0_0]
set_property IOSTANDARD LVCMOS33 [get_ports a0_0]
set_property PACKAGE_PIN C7 [get_ports not_cs_0]
set_property IOSTANDARD LVCMOS33 [get_ports not_cs_0]

set_property PACKAGE_PIN P8 [get_ports {gpio_rtl_2_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[0]}]
set_property PACKAGE_PIN R8 [get_ports {gpio_rtl_2_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[1]}]
set_property PACKAGE_PIN T7 [get_ports {gpio_rtl_2_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[2]}]
set_property PACKAGE_PIN T8 [get_ports {gpio_rtl_2_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[3]}]
set_property PACKAGE_PIN T9 [get_ports {gpio_rtl_2_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[4]}]
set_property PACKAGE_PIN T10 [get_ports {gpio_rtl_2_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[5]}]
set_property PACKAGE_PIN R5 [get_ports {gpio_rtl_2_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[6]}]
set_property PACKAGE_PIN T5 [get_ports {gpio_rtl_2_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_2_tri_o[7]}]

set_property PACKAGE_PIN J3 [get_ports {gpio_rtl_3_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_3_tri_i[0]}]
set_property PACKAGE_PIN H3 [get_ports {gpio_rtl_3_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_3_tri_i[1]}]

set_property PACKAGE_PIN C3 [get_ports uart_rtl_1_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_1_txd]
set_property PACKAGE_PIN C2 [get_ports uart_rtl_1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_1_rxd]


set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[0]}]

set_property PACKAGE_PIN N4 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0]


set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]


set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io0_io]

set_property PACKAGE_PIN L12 [get_ports {spi_rtl_0_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_rtl_0_ss_io[0]}]
set_property PACKAGE_PIN J13 [get_ports spi_rtl_0_io0_io]
set_property PACKAGE_PIN J14 [get_ports spi_rtl_0_io1_io]
set_property PACKAGE_PIN K15 [get_ports spi_rtl_0_io2_io]
set_property PACKAGE_PIN K16 [get_ports spi_rtl_0_io3_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_io3_io]

set_property PACKAGE_PIN M15 [get_ports spi_rtl_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_rtl_0_sck_io]

set_property PACKAGE_PIN N6 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[5]}]
set_property PACKAGE_PIN P4 [get_ports {gpio_rtl_1_tri_i[5]}]
set_property PACKAGE_PIN P1 [get_ports {gpio_rtl_1_tri_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[4]}]
set_property PACKAGE_PIN P3 [get_ports {gpio_rtl_1_tri_i[6]}]
set_property PACKAGE_PIN M5 [get_ports {gpio_rtl_1_tri_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_1_tri_i[7]}]

set_property PACKAGE_PIN M12 [get_ports uart_rtl_0_rxd]

set_property PACKAGE_PIN L2 [get_ports {gpio_rtl_1_tri_i[2]}]
set_property PACKAGE_PIN L3 [get_ports {gpio_rtl_1_tri_i[3]}]
set_property PACKAGE_PIN M1 [get_ports {gpio_rtl_0_tri_o[7]}]

set_property PACKAGE_PIN N1 [get_ports {gpio_rtl_0_tri_o[6]}]

set_property PACKAGE_PIN N2 [get_ports {gpio_rtl_0_tri_o[4]}]

set_property PACKAGE_PIN L5 [get_ports {gpio_rtl_0_tri_o[0]}]
set_property PACKAGE_PIN L4 [get_ports {gpio_rtl_0_tri_o[1]}]

set_property PACKAGE_PIN K2 [get_ports {gpio_rtl_1_tri_i[0]}]
set_property PACKAGE_PIN K3 [get_ports {gpio_rtl_1_tri_i[1]}]
set_property PACKAGE_PIN N3 [get_ports {gpio_rtl_0_tri_o[3]}]
set_property PACKAGE_PIN M4 [get_ports {gpio_rtl_0_tri_o[2]}]

set_property PACKAGE_PIN N11 [get_ports clk_100MHz]
set_property CLOCK_DEDICATED_ROUTE TRUE [get_nets design_1_i/clk_wiz_1/inst/clk_out1]

set_property PACKAGE_PIN M2 [get_ports {gpio_rtl_0_tri_o[5]}]
